public Class Mclass2
{
public Account createAccount(String name)  //method to create account
{
//Add comment for Account A1
Account a121 = new Account();
a121.Name = name;
return a121;

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//thank God, I am as good as the best.bad as the worst, but,I am as  thank God, I am as good as the best am as good as the .
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test
//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test
//this is the test 
//this is test
//the future way to predict is to create it.The best 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test
//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

//Do ybe treated. best. Treat our others Do right.  as you want to 
//this is test
//this is the test 
//this is test
//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test
//this is the test 
//this is test
//this is the test 
//this is test

//this is the test 
//this is test
//this is the test 
//this is test

}
}